[package]
name = "runnables-cli"
description = "cli to run executables in a workspace"
author = ["mbecker20 <becker.maxh@gmail.com>"]
license = "GPL-3.0-or-later"
edition = "2021"
version = "0.1.0"

[[bin]]
name = "run"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0.188", features = ["derive"] }
clap = { version = "4.4.4", features = ["derive"] }
indexmap = { version = "2.0.0", features = ["serde"] }
ratatui = { version = "0.23.0", features = ["all-widgets"] }
crossterm = "0.27.0"
tui-input = "0.8.0"
run_command = "0.0.6"
anyhow = "1.0.75"
toml = "0.8.0"
serde_json = "1.0.107"
path-clean = "1.0.1"
enum_cycling = "0.1.1"
derive_variants = "0.1.1"
colored = "2.0.4"
