[package]
name = "runnables-cli"
version = "0.1.0"
edition = "2021"
author = ["mbecker20 <becker.maxh@gmail.com>"]
description = "run any executable package in a workspace"
license = "GPL-3.0-or-later"

[[bin]]
name = "run"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0.188", features = ["derive"] }
clap = { version = "4.4.2", features = ["derive"] }
ratatui = { version = "0.23.0", features = ["all-widgets"] }
anyhow = "1.0.75"
toml = "0.7.8"
serde_json = "1.0.106"
log = "0.4.20"
simple_logger = "4.2.0"
path-clean = "1.0.1"
# cursive = "0.20.0"
